### PR TITLE
SW-153 bump version and small bugfixes

### PR DESCRIPTION
**Pull request by JFSolution**

### CODE REVIEW

**Comment by ahmed-mrbeam** [comment]
There are 3 commits here that are not related to SW-153 , do you know the reason ? @Josef-MrBeam

**Comment by JFSolution** [comment]
I added the versionbump directy to develop  without a separate branch, and axel did some bugfixes, these should be included in the beta

**Comment by ahmed-mrbeam** [comment]
> I added the versionbump directy to develop without a separate branch, and axel did some bugfixes, these should be included in the beta

We MUST not commit directly to develop, everything that goes to develop or matser, stable.. or any base branch has to be through a pull request.
So for now Please freeze this until we talk about it in the meeting

**Comment by ahmed-mrbeam** [comment]
No need to work on it, we need the version bump only in develop

**Pull request closed without merging**
